-- Operations and security hardening for durable ingestion (Items 35 and 38).
-- Apply to a disposable project first. All mutable objects remain service-role only.

begin;

alter table public.upload_jobs
  add column if not exists cancel_requested_at timestamptz,
  add column if not exists cancel_requested_by uuid,
  add column if not exists cancel_reason text,
  add column if not exists cancelled_at timestamptz;

alter table public.upload_jobs drop constraint if exists upload_jobs_status_check;
alter table public.upload_jobs
  add constraint upload_jobs_status_check
  check (status in ('staging', 'queued', 'processing', 'retry_wait', 'completed', 'failed', 'cancelled'));

create index if not exists upload_jobs_cancel_idx
  on public.upload_jobs (cancel_requested_at)
  where cancel_requested_at is not null and status = 'processing';

create table if not exists public.upload_job_events (
  id bigint generated by default as identity primary key,
  job_id uuid,
  owner_id uuid,
  department text,
  event_type text not null,
  status text not null,
  stage text,
  attempt_count integer not null default 0,
  worker_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Jobs expire after 30 days, while their sanitized lifecycle events remain for
-- 90 days.  Preserve that longer audit window without retaining the job row.
alter table public.upload_job_events
  drop constraint if exists upload_job_events_job_id_fkey;
alter table public.upload_job_events
  add constraint upload_job_events_job_id_fkey
  foreign key (job_id) references public.upload_jobs(id) on delete set null;

create index if not exists upload_job_events_job_idx
  on public.upload_job_events (job_id, created_at desc);
create index if not exists upload_job_events_expiry_idx
  on public.upload_job_events (created_at);

create table if not exists public.ingestion_workers (
  worker_id text primary key,
  state text not null default 'idle'
    check (state in ('starting', 'idle', 'processing', 'degraded', 'stopping')),
  current_job_id uuid,
  scanner_status text not null default 'unknown'
    check (scanner_status in ('unknown', 'disabled', 'healthy', 'unavailable')),
  version text not null default 'unknown',
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  stopped_at timestamptz
);

create index if not exists ingestion_workers_seen_idx
  on public.ingestion_workers (last_seen_at desc);

create table if not exists public.operational_alerts (
  id uuid primary key default gen_random_uuid(),
  dedupe_key text not null unique,
  alert_type text not null,
  severity text not null check (severity in ('info', 'warning', 'critical')),
  status text not null default 'open' check (status in ('open', 'acknowledged', 'resolved')),
  safe_details jsonb not null default '{}'::jsonb,
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_notified_at timestamptz,
  acknowledged_at timestamptz,
  acknowledged_by uuid,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists operational_alerts_status_idx
  on public.operational_alerts (status, severity, last_seen_at desc);

create table if not exists public.security_audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info', 'warning', 'critical')),
  department text,
  safe_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_audit_events_created_idx
  on public.security_audit_events (created_at desc);

create or replace function public.record_upload_job_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text;
begin
  if tg_op = 'INSERT' then
    v_type := 'reserved';
  elsif new.cancel_requested_at is distinct from old.cancel_requested_at
      and new.cancel_requested_at is not null then
    v_type := 'cancellation_requested';
  elsif new.status is distinct from old.status then
    v_type := 'status_changed';
  elsif new.stage is distinct from old.stage then
    v_type := 'stage_changed';
  elsif new.cleanup_status is distinct from old.cleanup_status then
    v_type := 'cleanup_changed';
  else
    return new;
  end if;

  insert into public.upload_job_events (
    job_id, owner_id, department, event_type, status, stage,
    attempt_count, worker_id, details
  ) values (
    new.id, new.owner_id, new.department, v_type, new.status, new.stage,
    new.attempt_count, new.lease_owner,
    jsonb_strip_nulls(jsonb_build_object(
      'progress', new.progress,
      'cleanup_status', new.cleanup_status,
      'failure_category', new.failure_category,
      'cancel_requested', new.cancel_requested_at is not null
    ))
  );
  return new;
end;
$$;

drop trigger if exists record_upload_job_event on public.upload_jobs;
create trigger record_upload_job_event
after insert or update on public.upload_jobs
for each row execute function public.record_upload_job_event();

-- Existing retained jobs receive an honest current-state snapshot, not fabricated history.
insert into public.upload_job_events (
  job_id, owner_id, department, event_type, status, stage,
  attempt_count, worker_id, details, created_at
)
select j.id, j.owner_id, j.department, 'migration_snapshot', j.status, j.stage,
  j.attempt_count, j.lease_owner,
  jsonb_build_object('cleanup_status', j.cleanup_status), now()
from public.upload_jobs j
where not exists (
  select 1 from public.upload_job_events e where e.job_id = j.id
);

create or replace function public.request_upload_cancellation(
  p_job_id uuid,
  p_requester_id uuid,
  p_is_superadmin boolean default false,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job public.upload_jobs%rowtype;
  v_outcome text;
begin
  select * into v_job from public.upload_jobs where id = p_job_id for update;
  if v_job.id is null then
    return jsonb_build_object('outcome', 'not_found');
  end if;
  if not coalesce(p_is_superadmin, false) and v_job.owner_id is distinct from p_requester_id then
    return jsonb_build_object('outcome', 'forbidden');
  end if;
  if v_job.status in ('completed', 'failed', 'cancelled') then
    return jsonb_build_object('outcome', 'already_terminal', 'status', v_job.status);
  end if;

  if v_job.status = 'processing' then
    update public.upload_jobs
    set cancel_requested_at = coalesce(cancel_requested_at, now()),
        cancel_requested_by = coalesce(cancel_requested_by, p_requester_id),
        cancel_reason = left(nullif(trim(p_reason), ''), 200),
        message = 'Cancellation requested. The worker will stop at the next safe checkpoint.',
        updated_at = now()
    where id = p_job_id;
    v_outcome := 'cancellation_requested';
  else
    update public.upload_jobs
    set status = 'cancelled', stage = 'cancelled', progress = 100,
        message = 'Upload cancelled.', error = null,
        cancel_requested_at = coalesce(cancel_requested_at, now()),
        cancel_requested_by = coalesce(cancel_requested_by, p_requester_id),
        cancel_reason = left(nullif(trim(p_reason), ''), 200),
        cancelled_at = now(), completed_at = now(),
        expires_at = now() + interval '30 days',
        cleanup_status = case when source_stored then 'pending' else 'not_required' end,
        next_retry_at = null, lease_owner = null, lease_expires_at = null,
        heartbeat_at = null, updated_at = now()
    where id = p_job_id;
    v_outcome := 'cancelled';
  end if;
  return (
    select jsonb_build_object(
      'outcome', v_outcome,
      'status', status,
      'cancel_requested', cancel_requested_at is not null,
      'cancelled_at', cancelled_at
    ) from public.upload_jobs where id = p_job_id
  );
end;
$$;

create or replace function public.heartbeat_upload_job_control(
  p_job_id uuid,
  p_worker_id text,
  p_lease_seconds integer default 120,
  p_stage text default null,
  p_progress integer default null,
  p_message text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cancel_requested boolean;
begin
  update public.upload_jobs
  set lease_expires_at = now() + make_interval(secs => p_lease_seconds),
      heartbeat_at = now(), stage = coalesce(p_stage, stage),
      progress = coalesce(p_progress, progress),
      message = case when cancel_requested_at is null then coalesce(p_message, message) else message end,
      updated_at = now()
  where id = p_job_id and status = 'processing'
    and lease_owner = p_worker_id and lease_expires_at >= now()
  returning cancel_requested_at is not null into v_cancel_requested;
  if not found then
    return jsonb_build_object('lease_valid', false, 'cancel_requested', false);
  end if;
  return jsonb_build_object('lease_valid', true, 'cancel_requested', v_cancel_requested);
end;
$$;

create or replace function public.finalize_upload_cancellation(
  p_job_id uuid,
  p_worker_id text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.upload_jobs
  set status = 'cancelled', stage = 'cancelled', progress = 100,
      message = 'Upload cancelled.', error = null,
      cancelled_at = now(), completed_at = now(),
      expires_at = now() + interval '30 days',
      cleanup_status = case when source_stored then 'pending' else 'not_required' end,
      next_retry_at = null, lease_owner = null, lease_expires_at = null,
      heartbeat_at = null, updated_at = now()
  where id = p_job_id and status = 'processing'
    and lease_owner = p_worker_id and lease_expires_at >= now()
    and cancel_requested_at is not null;
  return found;
end;
$$;

create or replace function public.register_ingestion_worker(
  p_worker_id text,
  p_state text,
  p_scanner_status text,
  p_version text,
  p_current_job_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(trim(p_worker_id), '') is null then raise exception 'Worker ID is required'; end if;
  insert into public.ingestion_workers (
    worker_id, state, scanner_status, version, current_job_id,
    started_at, last_seen_at, stopped_at
  ) values (
    p_worker_id, p_state, p_scanner_status, left(coalesce(p_version, 'unknown'), 80),
    p_current_job_id, now(), now(), null
  )
  on conflict (worker_id) do update set
    state = excluded.state, scanner_status = excluded.scanner_status,
    version = excluded.version, current_job_id = excluded.current_job_id,
    last_seen_at = now(), stopped_at = null;
  return true;
end;
$$;

create or replace function public.stop_ingestion_worker(p_worker_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ingestion_workers
  set state = 'stopping', current_job_id = null, last_seen_at = now(), stopped_at = now()
  where worker_id = p_worker_id;
  return found;
end;
$$;

create or replace function public.apply_operations_retention(p_apply boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_events bigint;
  v_alerts bigint;
  v_security bigint;
begin
  select count(*) into v_events from public.upload_job_events
    where created_at < now() - interval '90 days';
  select count(*) into v_alerts from public.operational_alerts
    where status = 'resolved' and resolved_at < now() - interval '90 days';
  select count(*) into v_security from public.security_audit_events
    where created_at < now() - interval '1 year';
  if coalesce(p_apply, false) then
    delete from public.upload_job_events where created_at < now() - interval '90 days';
    delete from public.operational_alerts
      where status = 'resolved' and resolved_at < now() - interval '90 days';
    delete from public.security_audit_events where created_at < now() - interval '1 year';
  end if;
  return jsonb_build_object(
    'applied', coalesce(p_apply, false),
    'upload_job_events', v_events,
    'resolved_operational_alerts', v_alerts,
    'security_audit_events', v_security
  );
end;
$$;

-- Cancellation-aware replacements for queue claim, retry, commit, cleanup, and expiry.
create or replace function public.claim_upload_job(p_worker_id text, p_lease_seconds integer default 120)
returns setof public.upload_jobs
language plpgsql security definer set search_path = public
as $$
declare v_job_id uuid;
begin
  if nullif(trim(p_worker_id), '') is null or p_lease_seconds not between 30 and 900 then
    raise exception 'Invalid worker lease request';
  end if;
  update public.upload_jobs
  set status = 'failed', stage = 'error', progress = 100,
      message = 'Private source staging did not complete.', error = 'Please submit the manuscript again.',
      failure_category = 'staging_timeout', source_stored = source_path is not null,
      cleanup_status = case when source_path is not null then 'pending' else 'not_required' end,
      completed_at = now(), expires_at = now() + interval '30 days', updated_at = now()
  where status = 'staging' and updated_at < now() - interval '15 minutes'
    and cancel_requested_at is null;
  update public.upload_jobs
  set status = 'cancelled', stage = 'cancelled', progress = 100,
      message = 'Upload cancelled.', cancelled_at = now(), completed_at = now(),
      expires_at = now() + interval '30 days',
      cleanup_status = case when source_stored then 'pending' else 'not_required' end,
      lease_owner = null, lease_expires_at = null, heartbeat_at = null, updated_at = now()
  where status = 'processing' and lease_expires_at < now() and cancel_requested_at is not null;
  update public.upload_jobs
  set status = 'failed', stage = 'error', progress = 100,
      message = 'Ingestion could not complete after the allowed retries.',
      error = 'Please submit the manuscript again later.',
      failure_category = coalesce(failure_category, 'worker_lease_expired'),
      cleanup_status = case when source_stored then 'pending' else 'not_required' end,
      completed_at = now(), expires_at = now() + interval '30 days',
      lease_owner = null, lease_expires_at = null, updated_at = now()
  where status = 'processing' and lease_expires_at < now()
    and attempt_count >= max_attempts and cancel_requested_at is null;
  select id into v_job_id from public.upload_jobs
  where (status = 'queued'
      or (status = 'retry_wait' and coalesce(next_retry_at, now()) <= now())
      or (status = 'processing' and lease_expires_at < now()))
    and cancel_requested_at is null and attempt_count < max_attempts and source_stored = true
  order by coalesce(next_retry_at, created_at), created_at
  for update skip locked limit 1;
  if v_job_id is null then return; end if;
  return query update public.upload_jobs
  set status = 'processing', stage = 'download', progress = 10,
      message = 'Durable worker claimed the ingestion job.', attempt_count = attempt_count + 1,
      lease_owner = p_worker_id,
      lease_expires_at = now() + make_interval(secs => p_lease_seconds),
      heartbeat_at = now(), started_at = coalesce(started_at, now()), updated_at = now()
  where id = v_job_id returning *;
end;
$$;

create or replace function public.schedule_upload_retry(
  p_job_id uuid, p_worker_id text, p_retry_at timestamptz, p_failure_category text
)
returns boolean language plpgsql security definer set search_path = public
as $$
begin
  update public.upload_jobs set status = 'retry_wait',
      message = 'A temporary service problem occurred. The job will retry automatically.',
      error = null, failure_category = left(p_failure_category, 120),
      next_retry_at = greatest(p_retry_at, now()),
      lease_owner = null, lease_expires_at = null, heartbeat_at = null, updated_at = now()
  where id = p_job_id and status = 'processing' and lease_owner = p_worker_id
    and lease_expires_at >= now() and attempt_count < max_attempts
    and cancel_requested_at is null;
  return found;
end;
$$;

create or replace function public.commit_upload_ingestion(
  p_job_id uuid, p_worker_id text, p_paper jsonb, p_chunks jsonb
)
returns uuid language plpgsql security definer set search_path = public
as $$
declare v_job public.upload_jobs%rowtype; v_paper_id uuid;
begin
  select * into v_job from public.upload_jobs where id = p_job_id for update;
  if v_job.id is null then raise exception 'Upload job not found'; end if;
  if v_job.status = 'completed' and v_job.paper_id is not null then return v_job.paper_id; end if;
  if v_job.cancel_requested_at is not null then raise exception 'Upload cancellation was requested'; end if;
  if v_job.status <> 'processing' or v_job.lease_owner is distinct from p_worker_id
      or v_job.lease_expires_at < now() then raise exception 'Upload worker lease is no longer valid'; end if;
  if nullif(p_paper ->> 'id', '')::uuid is distinct from p_job_id then
    raise exception 'Paper identifier must match upload job';
  end if;
  v_paper_id := public.commit_paper_ingestion(p_paper, p_chunks);
  update public.upload_jobs set status = 'completed', stage = 'done', progress = 100,
      message = 'Thesis indexed successfully.', paper_id = v_paper_id,
      chunks = jsonb_array_length(p_chunks), duplication = p_paper -> 'duplication_scan',
      error = null, failure_category = null, cleanup_status = 'not_required',
      completed_at = now(), expires_at = now() + interval '30 days',
      lease_owner = null, lease_expires_at = null, heartbeat_at = now(), updated_at = now()
  where id = p_job_id;
  return v_paper_id;
end;
$$;

create or replace function public.claim_upload_cleanup(p_worker_id text)
returns setof public.upload_jobs language plpgsql security definer set search_path = public
as $$
declare v_job_id uuid;
begin
  select id into v_job_id from public.upload_jobs
  where status in ('failed', 'cancelled') and cleanup_status = 'pending' and source_stored = true
  order by completed_at nulls first, created_at for update skip locked limit 1;
  if v_job_id is null then return; end if;
  return query update public.upload_jobs
  set cleanup_status = 'processing', lease_owner = p_worker_id,
      lease_expires_at = now() + interval '120 seconds', updated_at = now()
  where id = v_job_id returning *;
end;
$$;

create or replace function public.expire_upload_jobs()
returns integer language plpgsql security definer set search_path = public
as $$
declare v_deleted integer;
begin
  update public.upload_jobs set cleanup_status = 'pending', lease_owner = null,
      lease_expires_at = null, updated_at = now()
  where cleanup_status = 'processing' and lease_expires_at < now();
  delete from public.upload_jobs where expires_at < now() and (
    (status = 'completed' and cleanup_status = 'not_required')
    or (status in ('failed', 'cancelled') and source_stored = false
      and cleanup_status in ('not_required', 'completed'))
  );
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

create or replace function public.upsert_operational_alert(
  p_dedupe_key text,
  p_alert_type text,
  p_severity text,
  p_safe_details jsonb default '{}'::jsonb
)
returns setof public.operational_alerts
language sql
security definer
set search_path = public
as $$
  insert into public.operational_alerts (
    dedupe_key, alert_type, severity, status, safe_details,
    occurrence_count, last_seen_at, updated_at, resolved_at
  ) values (
    left(p_dedupe_key, 160), left(p_alert_type, 120), p_severity,
    'open', coalesce(p_safe_details, '{}'::jsonb), 1, now(), now(), null
  )
  on conflict (dedupe_key) do update set
    alert_type = excluded.alert_type,
    severity = excluded.severity,
    status = case
      when public.operational_alerts.status = 'resolved' then 'open'
      else public.operational_alerts.status
    end,
    safe_details = excluded.safe_details,
    occurrence_count = public.operational_alerts.occurrence_count
      + case when public.operational_alerts.status = 'resolved' then 1 else 0 end,
    last_seen_at = now(),
    updated_at = now(),
    acknowledged_at = case
      when public.operational_alerts.status = 'resolved' then null
      else public.operational_alerts.acknowledged_at
    end,
    acknowledged_by = case
      when public.operational_alerts.status = 'resolved' then null
      else public.operational_alerts.acknowledged_by
    end,
    resolved_at = null
  returning *;
$$;

alter table public.upload_job_events enable row level security;
alter table public.ingestion_workers enable row level security;
alter table public.operational_alerts enable row level security;
alter table public.security_audit_events enable row level security;

revoke all on table public.upload_job_events, public.ingestion_workers,
  public.operational_alerts, public.security_audit_events from public, anon, authenticated;
revoke all on table public.upload_job_events, public.ingestion_workers,
  public.operational_alerts, public.security_audit_events from service_role;
grant select on table public.upload_job_events, public.ingestion_workers,
  public.operational_alerts, public.security_audit_events to service_role;
grant update on table public.operational_alerts to service_role;
grant insert on table public.security_audit_events to service_role;
grant usage, select on sequence public.security_audit_events_id_seq to service_role;

revoke all on function public.record_upload_job_event() from public, anon, authenticated;
revoke all on function public.request_upload_cancellation(uuid, uuid, boolean, text)
  from public, anon, authenticated;
revoke all on function public.heartbeat_upload_job_control(uuid, text, integer, text, integer, text)
  from public, anon, authenticated;
revoke all on function public.finalize_upload_cancellation(uuid, text)
  from public, anon, authenticated;
revoke all on function public.register_ingestion_worker(text, text, text, text, uuid)
  from public, anon, authenticated;
revoke all on function public.stop_ingestion_worker(text) from public, anon, authenticated;
revoke all on function public.apply_operations_retention(boolean) from public, anon, authenticated;
revoke all on function public.upsert_operational_alert(text, text, text, jsonb)
  from public, anon, authenticated;

grant execute on function public.request_upload_cancellation(uuid, uuid, boolean, text) to service_role;
grant execute on function public.heartbeat_upload_job_control(uuid, text, integer, text, integer, text)
  to service_role;
grant execute on function public.finalize_upload_cancellation(uuid, text) to service_role;
grant execute on function public.register_ingestion_worker(text, text, text, text, uuid) to service_role;
grant execute on function public.stop_ingestion_worker(text) to service_role;
grant execute on function public.apply_operations_retention(boolean) to service_role;
grant execute on function public.upsert_operational_alert(text, text, text, jsonb)
  to service_role;

-- Existing queue RPC grants remain service-role-only after replacement.
revoke all on function public.claim_upload_job(text, integer) from public, anon, authenticated;
revoke all on function public.schedule_upload_retry(uuid, text, timestamptz, text)
  from public, anon, authenticated;
revoke all on function public.commit_upload_ingestion(uuid, text, jsonb, jsonb)
  from public, anon, authenticated;
revoke all on function public.claim_upload_cleanup(text) from public, anon, authenticated;
revoke all on function public.expire_upload_jobs() from public, anon, authenticated;
grant execute on function public.claim_upload_job(text, integer) to service_role;
grant execute on function public.schedule_upload_retry(uuid, text, timestamptz, text) to service_role;
grant execute on function public.commit_upload_ingestion(uuid, text, jsonb, jsonb) to service_role;
grant execute on function public.claim_upload_cleanup(text) to service_role;
grant execute on function public.expire_upload_jobs() to service_role;

commit;
