function safeText(value) {
  return typeof value === 'string' ? value.trim() : ''
}

export function plainResponseText(answer) {
  return safeText(answer)
    .replace(/\[([^\]]+)]\(([^)]+)\)/g, '$1')
    .replace(/\[([0-9]+)\]/g, ' citation $1 ')
    .replace(/[*_`#>]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s+([.,;:!?])/g, '$1')
    .trim()
}

export async function copyText(text) {
  const value = safeText(text)
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(value)
    return
  }
  const helper = document.createElement('textarea')
  helper.value = value
  helper.style.position = 'fixed'
  helper.style.opacity = '0'
  document.body.appendChild(helper)
  helper.select()
  document.execCommand('copy')
  helper.remove()
}

export function responseWithSources(message) {
  const answer = safeText(message?.answer)
  const sources = Array.isArray(message?.sources) ? message.sources : []
  if (!sources.length) return answer
  const sourceList = sources.map((source) => {
    const citation = source.citation_id ? `[${source.citation_id}] ` : ''
    const author = safeText(source.authors)
    const year = source.year ? ` (${source.year})` : ''
    return `${citation}${safeText(source.title) || 'Archived thesis'}${author ? ` - ${author}` : ''}${year}`
  })
  return `${answer}\n\nEvidence sources\n${sourceList.join('\n')}`
}

export function downloadResearchNote(message) {
  const text = responseWithSources(message)
  const note = `IskAI research note\n\n${text}\n\nGenerated by the ISU Thesis AI Library. Verify important claims against the cited archive metadata.\n`
  const blob = new Blob([note], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = 'iskai-research-note.txt'
  anchor.click()
  URL.revokeObjectURL(url)
}

export function responseDetails(message) {
  const sources = Array.isArray(message?.sources) ? message.sources : []
  const studies = new Set(sources.map((source) => source.id).filter(Boolean)).size
  const citations = new Set(
    [...safeText(message?.answer).matchAll(/\[([0-9]+)]/g)].map((match) => match[1]),
  ).size
  return {
    type: message?.messageKind === 'notice' ? 'System response' : 'Research answer',
    generation: message?.notice_type === 'conversation' ? 'Local conversational response' : 'Archive-grounded RAG',
    citations,
    passages: sources.length,
    studies,
    archive: message?.archive_current ? 'Current indexed archive' : 'Saved response snapshot',
    createdAt: message?.createdAt || null,
  }
}
