"""Rebuild paper_CORRECTED.docx from the untouched 2026-08-09 original.

Every edit is declared here with an expected match count, so a wording drift in
the source raises instead of silently skipping a correction. Re-runnable: it
always starts from the original, so it can never double-apply.

Ground truth comes from the repository, not from prose:
  rag-thesis-backend/requirements.lock, config.py, Dockerfile
  rag-thesis-frontend/package.json, package-lock.json
  .github/workflows/quality.yml, docs/evidence (SonarQube/JMeter)
"""
import _docxlib as D

SRC = 'paper_ORIGINAL_2026-08-09.docx'
DST = 'paper_CORRECTED.docx'

# --- Tables 1-4 and 6: version cells -------------------------------------
CELLS = [
    ('v19.2.5',  'v19.2.8',  'T1 React'),
    ('v8.0.8',   'v8.1.5',   'T1 Vite'),
    ('v0.135.3', 'v0.139.2', 'T2 FastAPI'),
    ('v2.12.5',  'v2.13.4',  'T2 Pydantic'),
    ('v0.0.24',  'v0.0.32',  'T2 python-multipart'),
    ('v2.28.3',  'v2.31.0',  'T3 supabase'),
    ('v4.2.1',   'v4.3.1',   'T3 langchain-google-genai'),
    ('Gemini 1.5 Flash', 'Gemini 3.6 Flash', 'T3 LLM name'),
    ('gemini-1.5-flash', 'gemini-3.6-flash', 'T3 LLM id'),
    ('v8.1.1',   'v9.1.1',   'T4 PyTest'),
    ('v10.4',    'Community Build 26.7.0.124771', 'T4 SonarQube'),
    ('v3.1.0',   'v4.0.6',   'T4 Pylint'),
    ('v9.0.0',   'v9.39.5',  'T4 ESLint'),
]

# --- prose: model names, pipeline description, Table 6 -------------------
PROSE = [
    ("such as Gemini's text-embedding-004",
     'specifically Gemini Embedding 2 (models/gemini-embedding-2)', 1, 'embed prose A'),
    ('the Gemini text-embedding-004 model', 'the Gemini Embedding 2 model', 1, 'embed prose B'),
    ("powered by Gemini's text-embedding-004", 'powered by Gemini Embedding 2', 1, 'embed prose C'),
    ('Gemini text-embedding-004, Supabase pgvector',
     'Gemini Embedding 2, Supabase pgvector', 1, 'T6 embed'),
    ('via the Gemini 1.5 Flash model', 'via the Gemini 3.6 Flash model', 1, 'LLM prose'),
    # extraction is PyMuPDF; LangChain document loaders are not used.
    # A third "document loaders" mention in the Ch.2 literature review is a
    # general statement about RAG systems, not this build, and is left alone.
    ("LangChain's document loaders to process digitized CCSICT theses",
     'PyMuPDF to extract text directly from digitized CCSICT theses', 2, 'document loaders'),
    ("LangChain's 'RetrievalQA' chains will be engineered",
     'A LangChain Expression Language (LCEL) prompt-to-model chain will be engineered',
     1, 'RetrievalQA #1'),
    ("utilizing LangChain's RetrievalQA",
     'utilizing a LangChain Expression Language prompt-to-model chain', 1, 'RetrievalQA #2'),
    ("a context reordering algorithm, such as LangChain's LongContextReorder",
     "a context reordering algorithm re-implementing LangChain's LongContextReorder",
     1, 'LongContextReorder'),
    ('React v19.2.5, Vite v8.0.8, FastAPI v0.135.3',
     'React v19.2.8, Vite v8.1.5, FastAPI v0.139.2', 1, 'T6 Obj3 versions'),
    ('Empirical performance data on Faithfulness and Context Precision',
     'Empirical performance data on Answer Correctness (the paired baseline-versus-RAG '
     'comparison metric), reported alongside Faithfulness and Context Precision as '
     'RAG-only diagnostics', 1, 'T6 Obj2 metrics'),
]


# --- Priority 1/2/3: substantive corrections -----------------------------
# Wording keeps the proposal's future tense; only the claims change.
PROSE2 = [
    # P1-5  Objective 2 metric semantics (3.2.4)
    ('calculating automated reference-free scores for Faithfulness and Context Precision.',
     'calculating Answer Correctness against the faculty-validated ground truth as the '
     'paired metric on which the two pathways will be compared, together with Faithfulness '
     'and Context Precision as RAG-only diagnostics of grounding and retrieval quality. '
     'These Ragas metrics are reference-based rather than reference-free, since Answer '
     'Correctness consumes the faculty ground truth directly. Because the baseline pathway '
     'has no retriever, it returns no retrieved contexts to rank, so Context Precision '
     'cannot be computed for it and will be reported for the RAG pathway alone.',
     1, 'P1-5 metric semantics'),
    # P1-5  the inferential test runs on Answer Correctness (3.2.5)
    ('generated by the Ragas framework, particularly in terms of Faithfulness and Context Precision.',
     'generated by the Ragas framework, particularly in terms of Answer Correctness, which '
     'is the only metric both pathways can be scored on against the faculty-validated '
     'ground truth.',
     1, 'P1-5 inferential metric'),
    # P1-6  both duplication figures, the advisory tiers, and no auto-decision
    ('the model also generates a brief summary of the matched archival study.',
     'the model also generates a brief summary of the matched archival study. The system '
     'reports two distinct figures: the highest passage similarity found against the '
     "archive, and the matched-chunk coverage, being the percentage of the new manuscript's "
     'chunks whose nearest archived neighbour met the 85% threshold. Coverage drives an '
     'advisory verdict of clear, review_suggested below 50%, or high_overlap at 50% and '
     'above. The verdict is advisory only: the system never automatically accepts or '
     'rejects a proposed topic, and the decision remains with the student and their '
     'faculty adviser.',
     1, 'P1-6 duplication numbers'),
    # P2-10 digitization boundary
    ('conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing.',
     'conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing. Scanning '
     'physical manuscripts to PDF is an operational prerequisite carried out before '
     "ingestion: the system's digitization phase extracts and, where necessary, OCRs text "
     'from an uploaded PDF for semantic indexing, and does not itself perform scanning or '
     'emit a new searchable PDF.',
     1, 'P2-10 digitization boundary'),
    ('(Tesseract OCR or EasyOCR)', '(Tesseract OCR)', 1, 'P2-10 single OCR engine'),
    # P2-17 student and faculty manuscript categories
    ('The vector database is strictly limited to undergraduate theses generated within the '
     'CCSICT department.',
     'The vector database is strictly limited to theses generated within the CCSICT '
     'department, comprising both student (undergraduate) and faculty manuscripts, each '
     'labelled by category and filterable in browsing, chat retrieval, and analytics. The '
     'evaluation corpus for Objective 2 remains exactly the fifty (50) undergraduate theses '
     'selected under the corpus protocol; faculty-category manuscripts are excluded from '
     'that locked corpus by definition.',
     1, 'P2-17 thesis categories'),
    # P2-7  tokenizer proxy caveat
    ('configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries.',
     'configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries. Chunk sizes will be measured with the local '
     'cl100k_base tokenizer as a fixed, reproducible proxy, because the Gemini tokenizer is '
     'not publicly available; chunk boundaries are therefore exact for that proxy and '
     'approximate for the embedding model.',
     1, 'P2-7 tokenizer caveat'),
    # P2-8  the evaluated retrieval constants
    ('the pipeline will enforce a minimum cosine similarity threshold;',
     'the pipeline will enforce a minimum cosine similarity threshold of 0.30 over the five '
     'nearest chunks (top-k = 5);',
     1, 'P2-8 retrieval constants'),
    # P2-9  actor model
    ('which will accommodate distinct user roles.',
     'which will accommodate distinct user roles. These comprise a Guest Researcher '
     '(unauthenticated, scoped to the evaluation department, with no saved history and an '
     'optional one-time bot check), authenticated student and faculty accounts, an '
     'administrator role, and a superadmin role for cross-department administration and '
     'operations. Upload is administrator-default but may be granted to student and faculty '
     'accounts through a server-owned permission matrix.',
     1, 'P2-9 actor model'),
    # P2-12 Table 5 is the development workstation, not a system requirement
    ('To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts.',
     'To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts. Table 5 specifies the development workstation rather than a '
     'deployment requirement: all embedding and generation work is performed remotely '
     'through the Gemini API and OCR is CPU-bound, so the discrete GPU is not used by the '
     'architecture.',
     1, 'P2-12 hardware framing'),
    # P3-14 PII claim reduced to what is provable
    ('by ensuring that no personally identifiable information (PII)',
     'by applying deterministic pattern-based redaction of high-risk personally identifiable '
     'information (PII) at ingestion as a best-effort technical control, paired with '
     'mandatory human privacy review, so that no PII',
     1, 'P3-14 PII softening'),
]


def build(verbose=True):
    xml = D.read_xml(SRC)
    for old, new, label in CELLS:
        xml, _ = D.replace_cell(xml, old, new, expect=1, label=label)
        if verbose: print(f'  cell   {label:26s} {old} -> {new}')
    xml = D.replace_cell_nth(xml, 'text-embedding-004', 'Gemini Embedding 2', 0, 'T3 embed name')
    xml = D.replace_cell_nth(xml, 'text-embedding-004',
                             'models/gemini-embedding-2 (768 dimensions)', 0, 'T3 embed id')
    if verbose: print(f'  cell   {"T3 embedding model":26s} text-embedding-004 -> Gemini Embedding 2')
    for old, new, n, label in PROSE + PROSE2:
        xml = D.replace_runs(xml, old, new, expect=n, label=label)
        if verbose: print(f'  prose  {label}')
    return xml


if __name__ == '__main__':
    xml = build()
    D.write_xml(SRC, DST, xml)
    print(f'\nwrote {DST}')
