"""Rebuild paper_CORRECTED.docx from the untouched 2026-08-09 original.

Every edit is declared here with an expected match count, so a wording drift in
the source raises instead of silently skipping a correction. Re-runnable: it
always starts from the original, so it can never double-apply.

Ground truth comes from the repository, not from prose:
  rag-thesis-backend/requirements.lock, config.py, Dockerfile
  rag-thesis-frontend/package.json, package-lock.json
  .github/workflows/quality.yml, docs/evidence (SonarQube/JMeter)
"""
import _docxlib as D

SRC = 'paper_ORIGINAL_2026-08-09.docx'
DST = 'paper_CORRECTED.docx'

# --- Tables 1-4 and 6: version cells -------------------------------------
CELLS = [
    ('v19.2.5',  'v19.2.8',  'T1 React'),
    ('v8.0.8',   'v8.1.5',   'T1 Vite'),
    ('v0.135.3', 'v0.139.2', 'T2 FastAPI'),
    ('v2.12.5',  'v2.13.4',  'T2 Pydantic'),
    ('v0.0.24',  'v0.0.32',  'T2 python-multipart'),
    ('v2.28.3',  'v2.31.0',  'T3 supabase'),
    ('v4.2.1',   'v4.3.1',   'T3 langchain-google-genai'),
    ('Gemini 1.5 Flash', 'Gemini 3.6 Flash', 'T3 LLM name'),
    ('gemini-1.5-flash', 'gemini-3.6-flash', 'T3 LLM id'),
    ('v8.1.1',   'v9.1.1',   'T4 PyTest'),
    ('v10.4',    'Community Build 26.7.0.124771', 'T4 SonarQube'),
    ('v3.1.0',   'v4.0.6',   'T4 Pylint'),
    ('v9.0.0',   'v9.39.5',  'T4 ESLint'),
]

# --- prose: model names, pipeline description, Table 6 -------------------
PROSE = [
    ("such as Gemini's text-embedding-004",
     'specifically Gemini Embedding (models/gemini-embedding-001)', 1, 'embed prose A'),
    ('the Gemini text-embedding-004 model', 'the Gemini Embedding model', 1, 'embed prose B'),
    ("powered by Gemini's text-embedding-004", 'powered by Gemini Embedding', 1, 'embed prose C'),
    ('Gemini text-embedding-004, Supabase pgvector',
     'Gemini Embedding, Supabase pgvector', 1, 'T6 embed'),
    ('via the Gemini 1.5 Flash model', 'via the Gemini 3.6 Flash model', 1, 'LLM prose'),
    # extraction is PyMuPDF; LangChain document loaders are not used.
    # A third "document loaders" mention in the Ch.2 literature review is a
    # general statement about RAG systems, not this build, and is left alone.
    ("LangChain's document loaders to process digitized CCSICT theses",
     'PyMuPDF to extract text directly from digitized CCSICT theses', 2, 'document loaders'),
    ("LangChain's 'RetrievalQA' chains will be engineered",
     'A LangChain Expression Language (LCEL) prompt-to-model chain will be engineered',
     1, 'RetrievalQA #1'),
    ("utilizing LangChain's RetrievalQA",
     'utilizing a LangChain Expression Language prompt-to-model chain', 1, 'RetrievalQA #2'),
    ("a context reordering algorithm, such as LangChain's LongContextReorder",
     "a context reordering algorithm re-implementing LangChain's LongContextReorder",
     1, 'LongContextReorder'),
    ('React v19.2.5, Vite v8.0.8, FastAPI v0.135.3',
     'React v19.2.8, Vite v8.1.5, FastAPI v0.139.2', 1, 'T6 Obj3 versions'),
    ('Empirical performance data on Faithfulness and Context Precision',
     'Empirical performance data on Answer Correctness (the paired baseline-versus-RAG '
     'comparison metric), reported alongside Faithfulness and Context Precision as '
     'RAG-only diagnostics', 1, 'T6 Obj2 metrics'),
]


# --- Priority 1/2/3: substantive corrections -----------------------------
# Wording keeps the proposal's future tense; only the claims change.
PROSE2 = [
    # P1-5  Objective 2 metric semantics (3.2.4)
    ('calculating automated reference-free scores for Faithfulness and Context Precision.',
     'calculating Answer Correctness against the faculty-validated ground truth as the '
     'paired metric on which the two pathways will be compared, together with Faithfulness '
     'and Context Precision as RAG-only diagnostics of grounding and retrieval quality. '
     'These Ragas metrics are reference-based rather than reference-free, since Answer '
     'Correctness consumes the faculty ground truth directly. Because the baseline pathway '
     'has no retriever, it returns no retrieved contexts to rank, so Context Precision '
     'cannot be computed for it and will be reported for the RAG pathway alone.',
     1, 'P1-5 metric semantics'),
    # P1-5  the inferential test runs on Answer Correctness (3.2.5)
    ('generated by the Ragas framework, particularly in terms of Faithfulness and Context Precision.',
     'generated by the Ragas framework, particularly in terms of Answer Correctness, which '
     'is the only metric both pathways can be scored on against the faculty-validated '
     'ground truth.',
     1, 'P1-5 inferential metric'),
    # P1-6  both duplication figures, the advisory tiers, and no auto-decision
    ('the model also generates a brief summary of the matched archival study.',
     'the model also generates a brief summary of the matched archival study. The system '
     'reports two distinct figures: the highest passage similarity found against the '
     "archive, and the matched-chunk coverage, being the percentage of the new manuscript's "
     'chunks whose nearest archived neighbour met the 85% threshold. Coverage drives an '
     'advisory verdict of clear, review_suggested below 50%, or high_overlap at 50% and '
     'above. The verdict is advisory only: the system never automatically accepts or '
     'rejects a proposed topic, and the decision remains with the student and their '
     'faculty adviser.',
     1, 'P1-6 duplication numbers'),
    # P2-10 digitization boundary
    ('conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing.',
     'conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing. Scanning '
     'physical manuscripts to PDF is an operational prerequisite carried out before '
     "ingestion: the system's digitization phase extracts and, where necessary, OCRs text "
     'from an uploaded PDF for semantic indexing, and does not itself perform scanning or '
     'emit a new searchable PDF.',
     1, 'P2-10 digitization boundary'),
    ('(Tesseract OCR or EasyOCR)', '(Tesseract OCR)', 1, 'P2-10 single OCR engine'),
    # P2-17 student and faculty manuscript categories
    ('The vector database is strictly limited to undergraduate theses generated within the '
     'CCSICT department.',
     'The vector database is strictly limited to theses generated within the CCSICT '
     'department, comprising both student (undergraduate) and faculty manuscripts, each '
     'labelled by category and filterable in browsing, chat retrieval, and analytics. The '
     'evaluation corpus for Objective 2 remains exactly the fifty (50) undergraduate theses '
     'selected under the corpus protocol; faculty-category manuscripts are excluded from '
     'that locked corpus by definition.',
     1, 'P2-17 thesis categories'),
    # P2-7  tokenizer proxy caveat
    ('configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries.',
     'configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries. Chunk sizes will be measured with the local '
     'cl100k_base tokenizer as a fixed, reproducible proxy, because the Gemini tokenizer is '
     'not publicly available; chunk boundaries are therefore exact for that proxy and '
     'approximate for the embedding model.',
     1, 'P2-7 tokenizer caveat'),
    # P2-8  the evaluated retrieval constants
    ('the pipeline will enforce a minimum cosine similarity threshold;',
     'the pipeline will enforce a minimum cosine similarity threshold of 0.30 over the five '
     'nearest chunks (top-k = 5);',
     1, 'P2-8 retrieval constants'),
    # P2-9  actor model
    ('which will accommodate distinct user roles.',
     'which will accommodate distinct user roles. These comprise a Guest Researcher '
     '(unauthenticated, scoped to the evaluation department, with no saved history and an '
     'optional one-time bot check), authenticated student and faculty accounts, an '
     'administrator role, and a superadmin role for cross-department administration and '
     'operations. Upload is administrator-default but may be granted to student and faculty '
     'accounts through a server-owned permission matrix.',
     1, 'P2-9 actor model'),
    # P2-12 Table 5 is the development workstation, not a system requirement
    ('To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts.',
     'To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts. Table 5 specifies the development workstation rather than a '
     'deployment requirement: all embedding and generation work is performed remotely '
     'through the Gemini API and OCR is CPU-bound, so the discrete GPU is not used by the '
     'architecture.',
     1, 'P2-12 hardware framing'),
    # P3-14 PII claim reduced to what is provable
    ('by ensuring that no personally identifiable information (PII)',
     'by applying deterministic pattern-based redaction of high-risk personally identifiable '
     'information (PII) at ingestion as a best-effort technical control, paired with '
     'mandatory human privacy review, so that no PII',
     1, 'P3-14 PII softening'),
]


# --- P1-3: dependencies the tables omit ----------------------------------
# Anchors must be unique to one table: "pgvector" and "Apache JMeter" also
# appear in Table 6, so Tables 3 and 4 are anchored on values written above.
TABLE_ROWS = [
    ('JavaScript (JSX)', 'Table 1 frontend', [
        ('Node.js', 'v24.18.0', 'Will provide the JavaScript runtime for the build toolchain, the development server, and the automated test runner.'),
        ('Tailwind CSS', 'v4.3.3', 'Will supply the utility-first styling layer applied consistently across all interface views.'),
        ('React Router', 'v8.3.0', 'Will handle client-side routing between the landing, archive, chat, and administrative views.'),
        ('TanStack Query', 'v5.101.4', 'Will manage server state, caching, and background refetching for API-backed views.'),
        ('Axios', 'v1.18.1', 'Will serve as the HTTP client for all requests from the frontend to the FastAPI backend.'),
        ('Framer Motion', 'v12.42.2', 'Will provide the animation and transition primitives used by the interface components.'),
    ]),
    ('python-dotenv', 'Table 2 backend', [
        ('Python', 'v3.14.7', 'Will serve as the backend runtime, pinned to an exact patch level and asserted at container build time.'),
        ('pydantic-settings', 'v2.14.2', 'Will load and validate server configuration from environment variables at startup.'),
        ('Uvicorn', 'v0.51.0', 'Will run the ASGI server hosting the FastAPI application.'),
        ('SlowAPI', 'v0.1.10', 'Will enforce per-route and default rate limits that protect the API from abuse and runaway cost.'),
        ('redis (Python client)', 'v8.0.1', 'Will connect the API to the Redis server (redis 8.6.4 in the operations compose file) that backs rate limiting and the shared daily guest token allowance.'),
        ('cryptography', 'v50.0.0', 'Will encrypt the storage backups written by scripts/storage_backup.py, using AES-GCM under a scrypt-derived key; pinned at v50.0.0 to clear CVE-2026-69247.'),
        ('PyJWT', 'v2.13.0', 'Will verify and read the Supabase-issued JSON Web Tokens: the assurance level behind the privileged multi-factor check and the user identity behind per-user rate limits. Tokens are issued by Supabase Auth, never by the backend.'),
        ('HTTPX', 'v0.28.1', 'Will perform outbound HTTP calls to Supabase and the Gemini API.'),
    ]),
    ('models/gemini-embedding-001 (768 dimensions)', 'Table 3 AI/RAG', [
        ('Gemini 3.5 Flash Lite', 'gemini-3.5-flash-lite', 'Will write the advisory verdict summaries and follow-up answers of novelty scans and serve as the Ragas judge in the Objective 2 evaluation; title-page metadata extraction runs on the primary generation model.'),
        ('langchain-core', 'v1.5.1', 'Will provide the Runnable and prompt abstractions that compose the retrieval-to-generation chain.'),
        ('langchain-text-splitters', 'v1.1.2', 'Will supply the RecursiveCharacterTextSplitter used to chunk extracted manuscript text.'),
        ('langchain-openai', 'v1.4.1', 'Will provide the OpenAI-compatible chat client used only when generation is routed through a gateway; embeddings are never routed through it.'),
        ('tiktoken', 'v0.13.0', 'Will provide the cl100k_base tokenizer used as a fixed proxy for measuring chunk sizes.'),
        ('PyMuPDF', 'v1.28.0', 'Will extract text and layout information directly from uploaded PDF manuscripts.'),
        ('tesserocr', 'v2.10.0', 'Will bind the Tesseract OCR engine for image-based scanned pages.'),
        ('Pillow', 'v12.3.0', 'Will handle page image preparation on the OCR path.'),
        ('LangSmith', 'v0.10.10', 'Will trace and log pipeline latency and token consumption during evaluation runs.'),
    ]),
    ('Community Build 26.7.0.124771', 'Table 4 testing', [
        ('Node.js test runner', 'v24.18.0 (node --test)', "Will execute the frontend unit test suite using the runtime's built-in test runner."),
        ('Playwright', 'v1.61.1', 'Will drive end-to-end browser tests across the critical user journeys of the interface.'),
        ('axe-core for Playwright', 'v4.12.1', 'Will perform automated accessibility checks within the end-to-end suite.'),
        ('SonarScanner CLI', 'v8.0.1.6346', 'Will submit the analysis to the SonarQube server that produces the retained Reliability evidence.'),
    ]),
]


# --- final additions: fingerprint, citation limit, production surround ---
PROSE3 = [
    # P1-1  the model set is frozen for the evaluation
    ('retrieve highly similar vector embeddings from the Supabase database before '
     'synthesizing a response.',
     'retrieve highly similar vector embeddings from the Supabase database before '
     'synthesizing a response. The effective model set, comprising the chat, verdict, and '
     'embedding models together with the generation and retrieval parameters, will be '
     'frozen in a signed release fingerprint for the duration of the evaluation, so that '
     'every reported result is attributable to one exact configuration. The fingerprint '
     'will additionally record which provider served the generation calls, so that a '
     'reported result cannot be attributed to the wrong route.',
     1, 'P1-1 release fingerprint'),
    # P3-15 what citation validation does and does not prove
    ('produce highly traceable, accurate in-line citations.',
     'produce highly traceable, accurate in-line citations. Citation validation will prove '
     'marker validity and coverage, meaning that every substantive claim in an answer '
     'carries a valid, in-range citation, but it does not establish semantic entailment '
     'between a claim and the passage it cites; faculty verification therefore remains part '
     'of the process.',
     1, 'P3-15 citation limitation'),
    # P3-16 / P2-11  production surround. Figure 8 itself is an embedded image and
    # still shows a synchronous upload path; this states the real one in text.
    ('As illustrated in Figure 8, the system architecture will be structured into four '
     'primary interactive layers: the User Interface Layer, the Application Layer, the '
     'Embedding Layer, and the Data Storage Layer.',
     'As illustrated in Figure 8, the system architecture will be structured into four '
     'primary interactive layers: the User Interface Layer, the Application Layer, the '
     'Embedding Layer, and the Data Storage Layer. Figure 8 depicts the experimental '
     'retrieval pipeline; the delivered platform surrounds that pipeline with '
     'production-grade controls which fall outside the experimental scope but are necessary '
     'for institutional deployment. Ingestion in particular runs asynchronously rather than '
     'synchronously: an upload is validated and staged privately, enqueued as a durable '
     'leased job, and processed by a separate worker that downloads, scans for malware, '
     'extracts, chunks, embeds, and screens the manuscript before an atomic commit. '
     'Authentication with row-level security, multi-factor administrative access, rate '
     'limiting, and malware scanning apply as cross-cutting controls across all four layers.',
     1, 'P3-16 production surround'),
]


# --- Sweep findings, 2026-08-25 ------------------------------------------
# A full read of all 427 non-empty paragraphs found that six revisions had
# been applied to only ONE of the sections they named, plus three inaccuracies
# neither the 08-03 comparison nor the first correction pass had caught.
PROSE4 = [
    # A1/A3  rev 17 + rev 10, section 3.1.3 (only 1.3 had been updated)
    ('The data will only include past undergraduate thesis projects from the department, '
     'using both physical hardbound copies and digital files.',
     'The data will include past student (undergraduate) and faculty thesis projects from '
     'the department, each labelled by category, using both physical hardbound copies and '
     'digital files. The evaluation corpus for Objective 2 remains exactly the fifty (50) '
     'student manuscripts. Converting physical copies into PDF is an operational '
     'prerequisite carried out before ingestion; the system extracts and, where necessary, '
     'OCRs text from an uploaded PDF and does not itself perform scanning.',
     1, 'A1/A3 3.1.3 corpus + boundary'),
    # A2  rev 17, section 3.2.1
    ('This approach ensures that the evaluation covers diverse technical vocabularies '
     'relevant to the domain.',
     'This approach ensures that the evaluation covers diverse technical vocabularies '
     'relevant to the domain. Every archived manuscript carries a student or faculty '
     'category label, and the Objective 2 evaluation corpus is restricted to student '
     '(undergraduate) manuscripts.',
     1, 'A2 3.2.1 category sentence'),
    # A4  rev 10, section 3.2.3 Phase 1
    ('Physical, hardbound thesis manuscripts from the CCSICT archives will be converted '
     'into machine-readable digital formats (PDFs).',
     'Physical, hardbound thesis manuscripts from the CCSICT archives will be converted '
     'into machine-readable digital formats (PDFs). That conversion is an operational '
     "prerequisite performed outside the application; the system's digitization phase "
     'begins with an uploaded PDF.',
     1, 'A4 Phase 1 boundary'),
    # A5  rev 6, section 3.2.3 Phase 3
    ('This triggers an automated warning for the AI model, ensuring that any potential '
     'duplicates are clearly identified in the output along with their exact match percentage.',
     'This triggers an automated warning for the AI model, ensuring that any potential '
     'duplicates are clearly identified in the output along with their exact match '
     'percentage. Two figures are reported: the highest passage similarity and the '
     "matched-chunk coverage, being the percentage of the new manuscript's chunks whose "
     'nearest archived neighbour met the threshold. Coverage drives an advisory verdict of '
     'clear, review_suggested below 50%, or high_overlap at 50% and above, and the verdict '
     'is advisory only — the system never automatically accepts or rejects a topic.',
     1, 'A5 Phase 3 duplication numbers'),
    # A6  rev 8, section 3.3
    ('which will search the Vector Database for the most semantically relevant thesis chunks.',
     'which will search the Vector Database for the most semantically relevant thesis '
     'chunks, applying a minimum cosine similarity of 0.30 and returning at most five '
     '(top-k = 5).',
     1, 'A6 3.3 retrieval constants'),
    # B1  the 1.5 definition still said undergraduate-only
    ('indirect access to undergraduate thesis knowledge',
     'indirect access to CCSICT student and faculty thesis knowledge',
     1, 'B1 1.5 definition'),
    # B2  analytics endpoints require an admin; only /analytics/summary is public
    ('a cohesive platform where students and faculty can execute literature reviews, '
     'conduct novelty scanning, and generate institutional research analytics.',
     'a cohesive platform where students and faculty can execute literature reviews and '
     'conduct novelty scanning, while administrators generate institutional research '
     'analytics.',
     1, 'B2 analytics is admin-only'),
    # B4  the paper understated its own approval protocol, which has four gates
    ('First, the researchers will obtain formal written approval from the CCSICT Department '
     'Chair and the University Librarian prior to accessing and digitizing any thesis '
     'manuscript from the college archives.',
     'First, the researchers will obtain formal written approval from four authorities '
     'prior to accessing and digitizing any thesis manuscript from the college archives: '
     'the CCSICT Department Chair for academic scope, the University Librarian for corpus '
     'custody and rights, an authorized privacy officer for the data-privacy review, and '
     'the thesis adviser for the final methodology and corpus.',
     1, 'B4 four approval gates'),
]


# --- Track vocabulary, resolved 2026-08-25 -------------------------------
# The academic catalog is authoritative. CCSICT has five programs but only
# three specializations: services/catalog.py:110 falls back to the program
# CODE when a program takes no specialization, and SPECIALIZATION_REQUIRED_
# PROGRAMS = {BSCS, BSIT} means those two can never be a track themselves.
# The legal papers.track values are therefore three specialization names plus
# three bare program codes. Phrasing mirrors golden_dataset.json, whose
# categories were realigned in commit 13f10c6, so the paper and the dataset
# cannot contradict each other.
PROSE5 = [
    ('ensuring representation across various academic tracks such as Data Mining, '
     'Web Development, and Network Security.',
     'ensuring representation across the CCSICT academic catalog: the Data Mining, '
     'Web and Mobile Application Development, and Network and Security specializations, '
     'together with the BSDSA, BSIS and BLIS programs, which carry no specialization and '
     'are therefore identified by program code.',
     1, 'Track vocabulary 3.2.1'),
]


# --- Figures -------------------------------------------------------------
# Figure 8 is an embedded PNG, so no text pass could ever reach it. The
# original labelled the Response Generator `gemini-1.5-flash`, the Embedding
# Model `text-embedding-004`, and the RAG Pipeline "LangChain &
# langchain-community" -- a dependency this project does not use -- while
# showing a retired "Researcher" actor with no superadmin and a synchronous
# upload path the system replaced with a durable queue. Every one of those
# contradicted the corrected body text.
#
# It is also resized here. The original drawing was 7.67 in wide on an A4 page
# with 1 in margins, i.e. 1.4 in past the right margin. The replacement is
# fitted to the measured text width, preserving its own aspect ratio.
FIGURES = [
    # Figure 1 (2.1.1) labelled the embedding step `text-embedding-004` and the
    # generation step "Gemini 1.5 Flash". Faithful redraw, same seven steps and
    # colours, with only those two model names corrected. Its original drawing was
    # also distorted: a 7.48 x 3.87 in extent, an aspect of 1.93 against the
    # image's native 2.33, so it was squashed as well as over-wide.
    ('media/image1.png', 'figures/figure1_rag_architecture.png', 'Figure 1 RAG flow'),
    ('media/image8.png', 'figures/figure8_system_architecture.png', 'Figure 8 architecture'),
]


# --- P6: the boundary of the no-training guarantee ------------------------
# The paper rests its data-governance argument on Google's Gemini API terms.
# `LLM_BASE_URL` (rag-thesis-backend/config.py:45) can route chat, extract and
# verdict calls to a third party those terms do not cover, so the guarantee has
# to be stated with its scope rather than unqualified.
PROSE6 = [
    ('ensuring compliance with Google’s API data governance policy (Google, 2024).',
     'ensuring compliance with Google’s API data governance policy (Google, 2024). '
     'This guarantee is bounded by the provider actually serving each call: the '
     'architecture permits generation to be routed through an OpenAI-compatible gateway '
     'without changing the model, and a third-party operator is not covered by those '
     'terms. The direct Google route will therefore be used for the formal evaluation and '
     'for any processing of the governed corpus, and the release fingerprint will record '
     'which route produced each result. Embedding calls are never routed and reach Google '
     'in every configuration.',
     1, 'P6-1 no-training guarantee scope'),
    ('Additionally, the indirect access model protects intellectual property by preventing '
     'users from viewing, downloading, or reproducing any full-text thesis content.',
     'Additionally, the indirect access model protects intellectual property by preventing '
     'users from viewing, downloading, or reproducing any full-text thesis content. Where '
     'the deployment routes generation through a third-party gateway rather than calling '
     'Google directly, that operator will be treated as a processor of institutional data '
     'and disclosed to the privacy review before any governed manuscript is processed '
     'through it.',
     1, 'P6-2 gateway disclosed to privacy review'),
]

# --- accuracy and citation-style corrections (2026-09-03 audit) ----------
PROSE7 = [
    # SonarQube's Python and JavaScript analysers do not detect memory leaks;
    # the reliability rating they produce is driven by bugs. The remaining
    # three items in the list are things the scan genuinely reports.
    ('logic flaws, unhandled exceptions, memory leaks, and potential fault points',
     'logic flaws, unhandled exceptions, and potential fault points',
     1, 'P7-1 SonarQube does not detect memory leaks'),

    # A Pylint score is only interpretable against the profile that produced
    # it. Ground truth: rag-thesis-backend/.pylintrc -- max-line-length=120,
    # ignore=venv,.venv,tests, and exactly fourteen disabled message families
    # (three docstring checks, five too-many-* checks, and six others). There
    # is no fail-under, so the score is informational rather than a gate.
    ('using linting tools such as Pylint for Python and ESLint for React to ensure code '
     'modularity, adherence to standards, and reduced technical debt.',
     'using linting tools such as Pylint for Python and ESLint for React to ensure code '
     'modularity, adherence to standards, and reduced technical debt. Pylint scores are '
     'reported against the configuration committed at rag-thesis-backend/.pylintrc, which '
     'raises the line-length limit to 120 characters, excludes the test suite from '
     'analysis, and disables fourteen message families including the docstring and '
     'function-size checks. The reported score is therefore comparable only against that '
     'profile.',
     1, 'P7-2 Pylint profile disclosed'),

    # APA 7: a work with three or more authors is cited as "first author et
    # al." at every mention, including the first. Section 2.1.5 already does
    # this for the same six-author paper; the synthesis in 2.1.7 did not.
    ('literature (Li, 2025;', 'literature (Li et al., 2025;',
     1, 'P7-3 Li et al. in-text citation'),

    # The Ragas scores are produced by a model, and the reader is entitled to
    # know which one. Anchored on the tail of the P1-5 replacement above,
    # because PROSE7 is applied after PROSE2. Ground truth: config.py:16-21
    # (gemini_chat_model, gemini_verdict_model, gemini_embed_model) and
    # evaluation/run_comparison.py:408-419.
    ('cannot be computed for it and will be reported for the RAG pathway alone.',
     'cannot be computed for it and will be reported for the RAG pathway alone. The Ragas '
     'metrics are themselves produced by a language model acting as judge. In this study '
     'the judge is Gemini 3.5 Flash-Lite scoring answers generated by Gemini 3.6 Flash, '
     'and the semantic component of Answer Correctness is embedded with Gemini Embedding '
     '(models/gemini-embedding-001), the same model the retriever indexes with. Judge and '
     'candidate therefore belong to one model family, and the judge shares the retriever '
     'embedding space. This is a limitation of the automated scores rather than a property '
     'of the architecture, and it is disclosed here so the reported figures are read as '
     'same-family automated judgements; anchoring them against a human-scored subsample '
     'remains open.',
     1, 'P7-4 same-family judge disclosed'),

    # How notices enter the diagnostics, and what accompanies the p-value.
    # Both are now what the harness actually emits
    # (summarize_rag_diagnostics and statistical_treatment), so the
    # methodology has to state them rather than leave them to be discovered
    # in the output.
    ('is the only metric both pathways can be scored on against the faculty-validated '
     'ground truth.',
     'is the only metric both pathways can be scored on against the faculty-validated '
     'ground truth. Two reporting rules follow from this. First, a no-evidence notice or a '
     'guard refusal is a correct system response rather than a research answer, yet it '
     'scores zero on Faithfulness and Context Precision while still carrying retrieved '
     'contexts; the three negative-control queries are expected to behave exactly this way. '
     'The RAG diagnostics are therefore reported for answers and for notices separately as '
     'well as pooled, and the separated figures are the ones interpreted as measures of '
     'grounding and retrieval quality. Second, because a p-value states only whether a '
     'difference is detectable at the achieved sample size, every reported comparison also '
     'carries the mean paired difference with a 95% confidence interval and a standardized '
     'effect size, so the magnitude of any difference is reported alongside its '
     'significance.',
     1, 'P7-5 notices rule and effect size'),
]


# --- Pass 8: dependency purposes and metric semantics (2026-09-03) ----------
# The Table 2 and Table 3 purpose cells are corrected in TABLE_ROWS above,
# because those rows are appended by this build and never existed in the
# original. The one prose fix: in Ragas 0.4.3 Faithfulness.ascore takes
# user_input, response and retrieved_contexts and no reference, so calling all
# three metrics reference-based was wrong. Only Answer Correctness and Context
# Precision (the with-reference variant) consume the ground truth. Ground
# truth: evaluation/run_comparison.py scoring calls and
# ragas.metrics.collections signatures.
PROSE8 = [
    ('These Ragas metrics are reference-based rather than reference-free, since Answer '
     'Correctness consumes the faculty ground truth directly.',
     'Answer Correctness and Context Precision are reference-based, since both consume the '
     'faculty ground truth directly, while Faithfulness is reference-free and is scored '
     'against the retrieved passages alone.',
     1, 'P8-1 which metrics use the reference'),
]


# --- P9: layout anchoring, table completeness, reference accuracy --------
# Chapter and reference headings were positioned with runs of empty
# paragraphs, which only hold while nothing above them moves. Eight passes of
# added rows and prose moved all three: page 12 was two-thirds blank before
# Chapter 2, while Chapter 3 and References had slid up into the middle of a
# page. Each heading is anchored to a page break instead, and the hand-typed
# spacers that were doing the job are removed.
PAGE_BREAKS = ['Chapter 1', 'Chapter 2', 'Chapter 3', 'References']
DROP_SPACERS = ['Chapter 2', 'Chapter 3', 'References']

# Two drawings were never refitted. Figure 2 sat at 7.58 in and Figure 7 at
# 7.73 in on a page whose text is 6.27 in wide, so both bled past the right
# margin and out to the left of the left one; Figure 7 was squashed as well,
# carrying a 1.99 aspect against the image's native 2.14. This is the fitting
# Figures 1 and 8 already receive, applied without replacing the artwork.
REFIT = [
    ('media/image2.png', 'P9-2 Figure 2 LLM errors'),
    ('media/image7.png', 'P9-2 Figure 7 iterative model'),
]

# Table 1 listed the animation library but not the client that carries the
# entire authentication flow (`supabase.auth` in AuthContext.jsx, api.js,
# MfaEnrollDialog.jsx and the password-reset pages). Table 4 named no security
# scanner at all although 3.2.5 promises "vulnerability counts identified
# through security scanning"; these four run on every push and pull request in
# .github/workflows/quality.yml.
TABLE_ROWS9 = [
    ('Framer Motion', 'P9-5 Table 1 auth client', [
        ('@supabase/supabase-js', 'v2.110.8',
         'Will provide the browser client for Supabase authentication, session refresh and '
         'multi-factor enrolment, on which the sign-in, sign-up and password-reset flows depend.'),
    ]),
    ('SonarScanner CLI', 'P9-6 Table 4 scanners', [
        ('Trivy', 'trivy-action v0.36.0',
         'Will scan both container images on every push and fail the pipeline on a CRITICAL or '
         'HIGH vulnerability that already has a fix available.'),
        ('Gitleaks', 'gitleaks-action v2',
         'Will scan the full commit history for committed credentials on every push and pull request.'),
        ('pip-audit', 'installed at run time',
         'Will audit the pinned Python dependency lock against the Python Packaging Advisory Database.'),
        ('npm audit', 'bundled with Node.js v24.18.0',
         'Will audit the production JavaScript dependency tree and fail on a high-severity advisory.'),
    ]),
]

PROSE9 = [
    # Table 5's third column is headed "Gap" and filled with "Feasible", with
    # nothing in the text saying what is being assessed against what.
    ('The table below lists the primary hardware used in this study.',
     'The table below lists the primary hardware used in this study. Its Gap column records the '
     'researchers’ readiness against each requirement: a component marked Feasible is already '
     'available on the development workstation, so nothing has to be procured before '
     'implementation begins.',
     1, 'P9-4 Table 5 Gap column explained'),
]

# Reference entries, each verified against the source itself rather than a
# lookup of the citation: Crossref's deposited record for the two DOIs, the
# arXiv listings, the article PDF for Doliente, and the ISSN register for the
# journal title. Five entries abbreviated author lists with "et al.", which
# APA 7 allows only in the in-text citation. Two carried worse than a style
# error - a fabricated author, and a DOI belonging to a different paper - so
# each edit is scoped to the one entry and stays inside a single run, which is
# what keeps the italic journal title beside it italic.
REFERENCES9 = [
    # Information Technology and Libraries 44(2); seven authors on the record.
    ('Bevara, R. V. K.',
     ', R. V. K., et al. (2025).',
     ', R. V. K., Lund, B. D., Mannuru, N. R., Karedla, S. P., Mohammed, Y., Kolapudi, S. T., '
     '& Mannuru, A. (2025).',
     'P9-7 Bevara authors'),
    # Five authors on the article's title page; the printed title ends "in the
    # Learning Common", and ISSN 2278-3083 registers the journal as *Applied*,
    # which its own masthead and Crossref record both use - only the running
    # header inside the PDF says "Advanced". Pages 29-37 were missing.
    ('Doliente, C. J. O.',
     ', C. J. O., et al. (2023).',
     ', C. J. O., Tual, D.-X., Paglinawan, Z. B., Naparan, J. A., & Facunla, H. L. (2023).',
     'P9-8 Doliente authors'),
    ('Doliente, C. J. O.',
     'in the learning commons.',
     'in the learning common.',
     'P9-8 Doliente title'),
    ('Doliente, C. J. O.',
     'International Journal of Science and Advanced Information Technology, 12',
     'International Journal of Science and Applied Information Technology, 12',
     'P9-8 Doliente journal'),
    ('Doliente, C. J. O.',
     '(4).',
     '(4), 29–37.',
     'P9-8 Doliente pages'),
    # "Dibia, V." is not an author of arXiv:2312.10997; the survey has ten.
    ('Dibia',
     'Gao, Y., Xiong, Y., Dibia, V., et al. (2024).',
     'Gao, Y., Xiong, Y., Gao, X., Jia, K., Pan, J., Bi, Y., Dai, Y., Sun, J., Wang, M., '
     '& Wang, H. (2024).',
     'P9-9 Gao authors'),
    # HiPerRAG has 24 authors, so APA 7 lists the first 19 and the last. The
    # DOI in the entry, 10.1109/ccgrid64434.2025.00035, resolves to "Evaluating
    # Energy Efficiency of AI Accelerators Using Two MLPerf Benchmarks" by
    # Ferdaus and colleagues - a different paper at a different conference.
    ('Gokdemir, O.,',
     'Gokdemir, O., et al. (2025). ',
     'Gokdemir, O., Siebenschuh, C., Brace, A., Wells, A., Hsu, B., Hippe, K., Setty, P., '
     'Ajith, A., Pauloski, J. G., Sastry, V., Foreman, S., Zheng, H., Ma, H., Kale, B., '
     'Chia, N., Gibbs, T., Papka, M., Brettin, T., Alexander, F., . . . Ramanathan, A. (2025). ',
     'P9-10 Gokdemir authors'),
    ('Gokdemir, O.,',
     'Proceedings of the 2025 IEEE/ACM International Symposium on Cluster, Cloud and '
     'Internet Computing (CCGrid)',
     'Proceedings of the Platform for Advanced Scientific Computing Conference (PASC 2025)',
     'P9-10 HiPerRAG venue'),
    ('Gokdemir, O.,',
     'https://doi.org/10.1109/ccgrid64434.2025.00035',
     'https://doi.org/10.1145/3732775.3733586',
     'P9-10 HiPerRAG DOI'),
    # arXiv:2502.14898 is by Lionel Wong and five colleagues, not "Wong, K.".
    ('Wong, K.',
     'Wong, K., et al. (2025).',
     'Wong, L., Ali, A., Xiong, R., Shen, S. Z., Kim, Y., & Agrawal, M. (2025).',
     'P9-11 Wong authors'),
]

# The displayed URL and the live hyperlink are stored separately; changing the
# text alone would leave the link still pointing at the wrong paper.
REL_TARGETS = [
    ('https://doi.org/10.1109/ccgrid64434.2025.00035',
     'https://doi.org/10.1145/3732775.3733586', 'P9-10 HiPerRAG link target'),
]


def apply_figures(xml, src, verbose=True):
    """Swap embedded figures and refit each drawing to the text width."""
    media = {}
    width_emu = D.text_width_emu(xml)
    for target, label in REFIT:
        pixels_w, pixels_h = D.png_pixels_bytes(D.media_bytes(src, target))
        cy = round(width_emu * pixels_h / pixels_w)
        rid = D.media_rid(src, target)
        xml = D.set_drawing_extent(xml, rid, width_emu, cy, label=label)
        xml = D.set_drawing_offset(xml, rid, 0, label=label)
        if verbose:
            print(f'  refit  {label:26s} ({pixels_w}x{pixels_h} px -> '
                  f'{width_emu/914400:.2f}x{cy/914400:.2f} in)')
    for target, source, label in FIGURES:
        payload = open(source, 'rb').read()
        pixels_w, pixels_h = D.png_pixels(source)
        cx = width_emu
        cy = round(width_emu * pixels_h / pixels_w)
        rid = D.media_rid(src, target)
        xml = D.set_drawing_extent(xml, rid, cx, cy, label=label)
        xml = D.set_drawing_offset(xml, rid, 0, label=label)
        media['word/' + target] = payload
        if verbose:
            print(f'  figure {label:26s} {source} '
                  f'({pixels_w}x{pixels_h} px -> {cx/914400:.2f}x{cy/914400:.2f} in)')
    return xml, media


def build(verbose=True):
    xml = D.read_xml(SRC)
    for old, new, label in CELLS:
        xml, _ = D.replace_cell(xml, old, new, expect=1, label=label)
        if verbose: print(f'  cell   {label:26s} {old} -> {new}')
    xml = D.replace_cell_nth(xml, 'text-embedding-004', 'Gemini Embedding', 0, 'T3 embed name')
    xml = D.replace_cell_nth(xml, 'text-embedding-004',
                             'models/gemini-embedding-001 (768 dimensions)', 0, 'T3 embed id')
    if verbose: print(f'  cell   {"T3 embedding model":26s} text-embedding-004 -> Gemini Embedding')
    for old, new, n, label in (
        PROSE + PROSE2 + PROSE3 + PROSE4 + PROSE5 + PROSE6 + PROSE7 + PROSE8 + PROSE9
    ):
        xml = D.replace_runs(xml, old, new, expect=n, label=label)
        if verbose: print(f'  prose  {label}')
    for anchor, label, rows in TABLE_ROWS + TABLE_ROWS9:
        xml, ncells = D.append_table_rows(xml, anchor, rows, label=label)
        if verbose: print(f'  rows   {label:18s} +{len(rows)} rows x {ncells} cells')
    # After the rows are in: the runtime was appended to the bottom of Table 2,
    # below python-dotenv, where a reader looks last for it.
    xml = D.move_table_row(xml, 'python-multipart', 'Python', 'FastAPI',
                           label='P9-3 Table 2 row order')
    if verbose: print(f'  order  {"Table 2 backend":18s} Python above FastAPI')
    for anchor, old, new, label in REFERENCES9:
        xml = D.replace_in_paragraph(xml, anchor, old, new, expect=1, label=label)
        if verbose: print(f'  ref    {label}')
    for text in DROP_SPACERS:
        xml, dropped = D.drop_blank_paragraphs_before(xml, text, label=f'P9-1 {text} spacers')
        if verbose: print(f'  layout {text:18s} -{dropped} spacer paragraphs')
    for text in PAGE_BREAKS:
        xml = D.set_page_break_before(xml, text, label=f'P9-1 {text} page break')
        if verbose: print(f'  layout {text:18s} starts a page')
    return xml


if __name__ == '__main__':
    xml = build()
    xml, media = apply_figures(xml, SRC)
    rels = D.read_xml(SRC, D.RELS)
    for old, new, label in REL_TARGETS:
        rels = D.set_rel_target(rels, old, new, label=label)
        print(f'  link   {label}')
    D.replace_parts(SRC, DST, {D.DOC: xml.encode('utf8'),
                               D.RELS: rels.encode('utf8'), **media})
    print(f'\nwrote {DST}')
