"""Rebuild paper_CORRECTED.docx from the untouched 2026-08-09 original.

Every edit is declared here with an expected match count, so a wording drift in
the source raises instead of silently skipping a correction. Re-runnable: it
always starts from the original, so it can never double-apply.

Ground truth comes from the repository, not from prose:
  rag-thesis-backend/requirements.lock, config.py, Dockerfile
  rag-thesis-frontend/package.json, package-lock.json
  .github/workflows/quality.yml, docs/evidence (SonarQube/JMeter)
"""
import _docxlib as D

SRC = 'paper_ORIGINAL_2026-08-09.docx'
DST = 'paper_CORRECTED.docx'

# --- Tables 1-4 and 6: version cells -------------------------------------
CELLS = [
    ('v19.2.5',  'v19.2.8',  'T1 React'),
    ('v8.0.8',   'v8.1.5',   'T1 Vite'),
    ('v0.135.3', 'v0.139.2', 'T2 FastAPI'),
    ('v2.12.5',  'v2.13.4',  'T2 Pydantic'),
    ('v0.0.24',  'v0.0.32',  'T2 python-multipart'),
    ('v2.28.3',  'v2.31.0',  'T3 supabase'),
    ('v4.2.1',   'v4.3.1',   'T3 langchain-google-genai'),
    ('Gemini 1.5 Flash', 'Gemini 3.6 Flash', 'T3 LLM name'),
    ('gemini-1.5-flash', 'gemini-3.6-flash', 'T3 LLM id'),
    ('v8.1.1',   'v9.1.1',   'T4 PyTest'),
    ('v10.4',    'Community Build 26.7.0.124771', 'T4 SonarQube'),
    ('v3.1.0',   'v4.0.6',   'T4 Pylint'),
    ('v9.0.0',   'v9.39.5',  'T4 ESLint'),
]

# --- prose: model names, pipeline description, Table 6 -------------------
PROSE = [
    ("such as Gemini's text-embedding-004",
     'specifically Gemini Embedding 2 (models/gemini-embedding-2)', 1, 'embed prose A'),
    ('the Gemini text-embedding-004 model', 'the Gemini Embedding 2 model', 1, 'embed prose B'),
    ("powered by Gemini's text-embedding-004", 'powered by Gemini Embedding 2', 1, 'embed prose C'),
    ('Gemini text-embedding-004, Supabase pgvector',
     'Gemini Embedding 2, Supabase pgvector', 1, 'T6 embed'),
    ('via the Gemini 1.5 Flash model', 'via the Gemini 3.6 Flash model', 1, 'LLM prose'),
    # extraction is PyMuPDF; LangChain document loaders are not used.
    # A third "document loaders" mention in the Ch.2 literature review is a
    # general statement about RAG systems, not this build, and is left alone.
    ("LangChain's document loaders to process digitized CCSICT theses",
     'PyMuPDF to extract text directly from digitized CCSICT theses', 2, 'document loaders'),
    ("LangChain's 'RetrievalQA' chains will be engineered",
     'A LangChain Expression Language (LCEL) prompt-to-model chain will be engineered',
     1, 'RetrievalQA #1'),
    ("utilizing LangChain's RetrievalQA",
     'utilizing a LangChain Expression Language prompt-to-model chain', 1, 'RetrievalQA #2'),
    ("a context reordering algorithm, such as LangChain's LongContextReorder",
     "a context reordering algorithm re-implementing LangChain's LongContextReorder",
     1, 'LongContextReorder'),
    ('React v19.2.5, Vite v8.0.8, FastAPI v0.135.3',
     'React v19.2.8, Vite v8.1.5, FastAPI v0.139.2', 1, 'T6 Obj3 versions'),
    ('Empirical performance data on Faithfulness and Context Precision',
     'Empirical performance data on Answer Correctness (the paired baseline-versus-RAG '
     'comparison metric), reported alongside Faithfulness and Context Precision as '
     'RAG-only diagnostics', 1, 'T6 Obj2 metrics'),
]


# --- Priority 1/2/3: substantive corrections -----------------------------
# Wording keeps the proposal's future tense; only the claims change.
PROSE2 = [
    # P1-5  Objective 2 metric semantics (3.2.4)
    ('calculating automated reference-free scores for Faithfulness and Context Precision.',
     'calculating Answer Correctness against the faculty-validated ground truth as the '
     'paired metric on which the two pathways will be compared, together with Faithfulness '
     'and Context Precision as RAG-only diagnostics of grounding and retrieval quality. '
     'These Ragas metrics are reference-based rather than reference-free, since Answer '
     'Correctness consumes the faculty ground truth directly. Because the baseline pathway '
     'has no retriever, it returns no retrieved contexts to rank, so Context Precision '
     'cannot be computed for it and will be reported for the RAG pathway alone.',
     1, 'P1-5 metric semantics'),
    # P1-5  the inferential test runs on Answer Correctness (3.2.5)
    ('generated by the Ragas framework, particularly in terms of Faithfulness and Context Precision.',
     'generated by the Ragas framework, particularly in terms of Answer Correctness, which '
     'is the only metric both pathways can be scored on against the faculty-validated '
     'ground truth.',
     1, 'P1-5 inferential metric'),
    # P1-6  both duplication figures, the advisory tiers, and no auto-decision
    ('the model also generates a brief summary of the matched archival study.',
     'the model also generates a brief summary of the matched archival study. The system '
     'reports two distinct figures: the highest passage similarity found against the '
     "archive, and the matched-chunk coverage, being the percentage of the new manuscript's "
     'chunks whose nearest archived neighbour met the 85% threshold. Coverage drives an '
     'advisory verdict of clear, review_suggested below 50%, or high_overlap at 50% and '
     'above. The verdict is advisory only: the system never automatically accepts or '
     'rejects a proposed topic, and the decision remains with the student and their '
     'faculty adviser.',
     1, 'P1-6 duplication numbers'),
    # P2-10 digitization boundary
    ('conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing.',
     'conversion of physical hardbound copies and unstructured digital softcopies from the '
     'CCSICT archives into searchable PDF formats suitable for semantic indexing. Scanning '
     'physical manuscripts to PDF is an operational prerequisite carried out before '
     "ingestion: the system's digitization phase extracts and, where necessary, OCRs text "
     'from an uploaded PDF for semantic indexing, and does not itself perform scanning or '
     'emit a new searchable PDF.',
     1, 'P2-10 digitization boundary'),
    ('(Tesseract OCR or EasyOCR)', '(Tesseract OCR)', 1, 'P2-10 single OCR engine'),
    # P2-17 student and faculty manuscript categories
    ('The vector database is strictly limited to undergraduate theses generated within the '
     'CCSICT department.',
     'The vector database is strictly limited to theses generated within the CCSICT '
     'department, comprising both student (undergraduate) and faculty manuscripts, each '
     'labelled by category and filterable in browsing, chat retrieval, and analytics. The '
     'evaluation corpus for Objective 2 remains exactly the fifty (50) undergraduate theses '
     'selected under the corpus protocol; faculty-category manuscripts are excluded from '
     'that locked corpus by definition.',
     1, 'P2-17 thesis categories'),
    # P2-7  tokenizer proxy caveat
    ('configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries.',
     'configured to an empirically optimized 800-token chunk size with a 100-token overlap '
     'to preserve contextual boundaries. Chunk sizes will be measured with the local '
     'cl100k_base tokenizer as a fixed, reproducible proxy, because the Gemini tokenizer is '
     'not publicly available; chunk boundaries are therefore exact for that proxy and '
     'approximate for the embedding model.',
     1, 'P2-7 tokenizer caveat'),
    # P2-8  the evaluated retrieval constants
    ('the pipeline will enforce a minimum cosine similarity threshold;',
     'the pipeline will enforce a minimum cosine similarity threshold of 0.30 over the five '
     'nearest chunks (top-k = 5);',
     1, 'P2-8 retrieval constants'),
    # P2-9  actor model
    ('which will accommodate distinct user roles.',
     'which will accommodate distinct user roles. These comprise a Guest Researcher '
     '(unauthenticated, scoped to the evaluation department, with no saved history and an '
     'optional one-time bot check), authenticated student and faculty accounts, an '
     'administrator role, and a superadmin role for cross-department administration and '
     'operations. Upload is administrator-default but may be granted to student and faculty '
     'accounts through a server-owned permission matrix.',
     1, 'P2-9 actor model'),
    # P2-12 Table 5 is the development workstation, not a system requirement
    ('To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts.',
     'To develop and test the system effectively, the researchers will use a laptop with '
     'specific hardware parts. Table 5 specifies the development workstation rather than a '
     'deployment requirement: all embedding and generation work is performed remotely '
     'through the Gemini API and OCR is CPU-bound, so the discrete GPU is not used by the '
     'architecture.',
     1, 'P2-12 hardware framing'),
    # P3-14 PII claim reduced to what is provable
    ('by ensuring that no personally identifiable information (PII)',
     'by applying deterministic pattern-based redaction of high-risk personally identifiable '
     'information (PII) at ingestion as a best-effort technical control, paired with '
     'mandatory human privacy review, so that no PII',
     1, 'P3-14 PII softening'),
]


# --- P1-3: dependencies the tables omit ----------------------------------
# Anchors must be unique to one table: "pgvector" and "Apache JMeter" also
# appear in Table 6, so Tables 3 and 4 are anchored on values written above.
TABLE_ROWS = [
    ('JavaScript (JSX)', 'Table 1 frontend', [
        ('Node.js', 'v24.18.0', 'Will provide the JavaScript runtime for the build toolchain, the development server, and the automated test runner.'),
        ('Tailwind CSS', 'v4.3.3', 'Will supply the utility-first styling layer applied consistently across all interface views.'),
        ('React Router', 'v8.3.0', 'Will handle client-side routing between the landing, archive, chat, and administrative views.'),
        ('TanStack Query', 'v5.101.4', 'Will manage server state, caching, and background refetching for API-backed views.'),
        ('Axios', 'v1.18.1', 'Will serve as the HTTP client for all requests from the frontend to the FastAPI backend.'),
        ('Framer Motion', 'v12.42.2', 'Will provide the animation and transition primitives used by the interface components.'),
    ]),
    ('python-dotenv', 'Table 2 backend', [
        ('Python', 'v3.14.7', 'Will serve as the backend runtime, pinned to an exact patch level and asserted at container build time.'),
        ('pydantic-settings', 'v2.14.2', 'Will load and validate server configuration from environment variables at startup.'),
        ('Uvicorn', 'v0.51.0', 'Will run the ASGI server hosting the FastAPI application.'),
        ('SlowAPI', 'v0.1.10', 'Will enforce per-route and default rate limits that protect the API from abuse and runaway cost.'),
        ('Redis', 'v8.0.1', 'Will provide the shared store backing rate limiting and short-lived operational state.'),
        ('cryptography', 'v50.0.0', 'Will supply the cryptographic primitives used for token and secret handling.'),
        ('PyJWT', 'v2.13.0', 'Will encode and verify the JSON Web Tokens used for authenticated sessions.'),
        ('HTTPX', 'v0.28.1', 'Will perform outbound HTTP calls to Supabase and the Gemini API.'),
    ]),
    ('models/gemini-embedding-2 (768 dimensions)', 'Table 3 AI/RAG', [
        ('Gemini 3.5 Flash Lite', 'gemini-3.5-flash-lite', 'Will handle bounded verdict and metadata-extraction work that does not require the primary generation model.'),
        ('langchain-core', 'v1.5.1', 'Will provide the Runnable and prompt abstractions that compose the retrieval-to-generation chain.'),
        ('langchain-text-splitters', 'v1.1.2', 'Will supply the RecursiveCharacterTextSplitter used to chunk extracted manuscript text.'),
        ('tiktoken', 'v0.13.0', 'Will provide the cl100k_base tokenizer used as a fixed proxy for measuring chunk sizes.'),
        ('PyMuPDF', 'v1.28.0', 'Will extract text and layout information directly from uploaded PDF manuscripts.'),
        ('tesserocr', 'v2.10.0', 'Will bind the Tesseract OCR engine for image-based scanned pages.'),
        ('Pillow', 'v12.3.0', 'Will handle page image preparation on the OCR path.'),
        ('LangSmith', 'v0.10.10', 'Will trace and log pipeline latency and token consumption during evaluation runs.'),
    ]),
    ('Community Build 26.7.0.124771', 'Table 4 testing', [
        ('Node.js test runner', 'v24.18.0 (node --test)', "Will execute the frontend unit test suite using the runtime's built-in test runner."),
        ('Playwright', 'v1.61.1', 'Will drive end-to-end browser tests across the critical user journeys of the interface.'),
        ('axe-core for Playwright', 'v4.12.1', 'Will perform automated accessibility checks within the end-to-end suite.'),
        ('SonarScanner CLI', 'v8.0.1.6346', 'Will submit the analysis to the SonarQube server that produces the retained Reliability evidence.'),
    ]),
]


# --- final additions: fingerprint, citation limit, production surround ---
PROSE3 = [
    # P1-1  the model set is frozen for the evaluation
    ('retrieve highly similar vector embeddings from the Supabase database before '
     'synthesizing a response.',
     'retrieve highly similar vector embeddings from the Supabase database before '
     'synthesizing a response. The effective model set, comprising the chat, verdict, and '
     'embedding models together with the generation and retrieval parameters, will be '
     'frozen in a signed release fingerprint for the duration of the evaluation, so that '
     'every reported result is attributable to one exact configuration.',
     1, 'P1-1 release fingerprint'),
    # P3-15 what citation validation does and does not prove
    ('produce highly traceable, accurate in-line citations.',
     'produce highly traceable, accurate in-line citations. Citation validation will prove '
     'marker validity and coverage, meaning that every substantive claim in an answer '
     'carries a valid, in-range citation, but it does not establish semantic entailment '
     'between a claim and the passage it cites; faculty verification therefore remains part '
     'of the process.',
     1, 'P3-15 citation limitation'),
    # P3-16 / P2-11  production surround. Figure 8 itself is an embedded image and
    # still shows a synchronous upload path; this states the real one in text.
    ('As illustrated in Figure 8, the system architecture will be structured into four '
     'primary interactive layers: the User Interface Layer, the Application Layer, the '
     'Embedding Layer, and the Data Storage Layer.',
     'As illustrated in Figure 8, the system architecture will be structured into four '
     'primary interactive layers: the User Interface Layer, the Application Layer, the '
     'Embedding Layer, and the Data Storage Layer. Figure 8 depicts the experimental '
     'retrieval pipeline; the delivered platform surrounds that pipeline with '
     'production-grade controls which fall outside the experimental scope but are necessary '
     'for institutional deployment. Ingestion in particular runs asynchronously rather than '
     'synchronously: an upload is validated and staged privately, enqueued as a durable '
     'leased job, and processed by a separate worker that downloads, scans for malware, '
     'extracts, chunks, embeds, and screens the manuscript before an atomic commit. '
     'Authentication with row-level security, multi-factor administrative access, rate '
     'limiting, and malware scanning apply as cross-cutting controls across all four layers.',
     1, 'P3-16 production surround'),
]


# --- Sweep findings, 2026-08-25 ------------------------------------------
# A full read of all 427 non-empty paragraphs found that six revisions had
# been applied to only ONE of the sections they named, plus three inaccuracies
# neither the 08-03 comparison nor the first correction pass had caught.
PROSE4 = [
    # A1/A3  rev 17 + rev 10, section 3.1.3 (only 1.3 had been updated)
    ('The data will only include past undergraduate thesis projects from the department, '
     'using both physical hardbound copies and digital files.',
     'The data will include past student (undergraduate) and faculty thesis projects from '
     'the department, each labelled by category, using both physical hardbound copies and '
     'digital files. The evaluation corpus for Objective 2 remains exactly the fifty (50) '
     'student manuscripts. Converting physical copies into PDF is an operational '
     'prerequisite carried out before ingestion; the system extracts and, where necessary, '
     'OCRs text from an uploaded PDF and does not itself perform scanning.',
     1, 'A1/A3 3.1.3 corpus + boundary'),
    # A2  rev 17, section 3.2.1
    ('This approach ensures that the evaluation covers diverse technical vocabularies '
     'relevant to the domain.',
     'This approach ensures that the evaluation covers diverse technical vocabularies '
     'relevant to the domain. Every archived manuscript carries a student or faculty '
     'category label, and the Objective 2 evaluation corpus is restricted to student '
     '(undergraduate) manuscripts.',
     1, 'A2 3.2.1 category sentence'),
    # A4  rev 10, section 3.2.3 Phase 1
    ('Physical, hardbound thesis manuscripts from the CCSICT archives will be converted '
     'into machine-readable digital formats (PDFs).',
     'Physical, hardbound thesis manuscripts from the CCSICT archives will be converted '
     'into machine-readable digital formats (PDFs). That conversion is an operational '
     "prerequisite performed outside the application; the system's digitization phase "
     'begins with an uploaded PDF.',
     1, 'A4 Phase 1 boundary'),
    # A5  rev 6, section 3.2.3 Phase 3
    ('This triggers an automated warning for the AI model, ensuring that any potential '
     'duplicates are clearly identified in the output along with their exact match percentage.',
     'This triggers an automated warning for the AI model, ensuring that any potential '
     'duplicates are clearly identified in the output along with their exact match '
     'percentage. Two figures are reported: the highest passage similarity and the '
     "matched-chunk coverage, being the percentage of the new manuscript's chunks whose "
     'nearest archived neighbour met the threshold. Coverage drives an advisory verdict of '
     'clear, review_suggested below 50%, or high_overlap at 50% and above, and the verdict '
     'is advisory only — the system never automatically accepts or rejects a topic.',
     1, 'A5 Phase 3 duplication numbers'),
    # A6  rev 8, section 3.3
    ('which will search the Vector Database for the most semantically relevant thesis chunks.',
     'which will search the Vector Database for the most semantically relevant thesis '
     'chunks, applying a minimum cosine similarity of 0.30 and returning at most five '
     '(top-k = 5).',
     1, 'A6 3.3 retrieval constants'),
    # B1  the 1.5 definition still said undergraduate-only
    ('indirect access to undergraduate thesis knowledge',
     'indirect access to CCSICT student and faculty thesis knowledge',
     1, 'B1 1.5 definition'),
    # B2  analytics endpoints require an admin; only /analytics/summary is public
    ('a cohesive platform where students and faculty can execute literature reviews, '
     'conduct novelty scanning, and generate institutional research analytics.',
     'a cohesive platform where students and faculty can execute literature reviews and '
     'conduct novelty scanning, while administrators generate institutional research '
     'analytics.',
     1, 'B2 analytics is admin-only'),
    # B4  the paper understated its own approval protocol, which has four gates
    ('First, the researchers will obtain formal written approval from the CCSICT Department '
     'Chair and the University Librarian prior to accessing and digitizing any thesis '
     'manuscript from the college archives.',
     'First, the researchers will obtain formal written approval from four authorities '
     'prior to accessing and digitizing any thesis manuscript from the college archives: '
     'the CCSICT Department Chair for academic scope, the University Librarian for corpus '
     'custody and rights, an authorized privacy officer for the data-privacy review, and '
     'the thesis adviser for the final methodology and corpus.',
     1, 'B4 four approval gates'),
]


def build(verbose=True):
    xml = D.read_xml(SRC)
    for old, new, label in CELLS:
        xml, _ = D.replace_cell(xml, old, new, expect=1, label=label)
        if verbose: print(f'  cell   {label:26s} {old} -> {new}')
    xml = D.replace_cell_nth(xml, 'text-embedding-004', 'Gemini Embedding 2', 0, 'T3 embed name')
    xml = D.replace_cell_nth(xml, 'text-embedding-004',
                             'models/gemini-embedding-2 (768 dimensions)', 0, 'T3 embed id')
    if verbose: print(f'  cell   {"T3 embedding model":26s} text-embedding-004 -> Gemini Embedding 2')
    for old, new, n, label in PROSE + PROSE2 + PROSE3 + PROSE4:
        xml = D.replace_runs(xml, old, new, expect=n, label=label)
        if verbose: print(f'  prose  {label}')
    for anchor, label, rows in TABLE_ROWS:
        xml, ncells = D.append_table_rows(xml, anchor, rows, label=label)
        if verbose: print(f'  rows   {label:18s} +{len(rows)} rows x {ncells} cells')
    return xml


if __name__ == '__main__':
    xml = build()
    D.write_xml(SRC, DST, xml)
    print(f'\nwrote {DST}')
